### ISSUE TITLE
MySQL Information overload

### ISSUE THREAD

**Issue by ZippyMagic** [ZippyMagician/CardBot#4]
I recently cloned this repository(not mine) created a table, and tested this out, and I discovered that a glitch somewhere in the code is causing a MySQL overload in data and corrupting the entire MySQL server. Plz fix this

**Comment by ZippyMagician** [comment]
I will review this and see if it is a problem

**Comment by ZippyMagician** [comment]
I researched this, and invalid MySQL setup will cause an overload in non-supported data. `invalid`
